// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package lov_field_model

import (
	"go-gin-example/pkg/model"
	"time"

	"gorm.io/gorm"
)

const TableNameLovField = "lov_field"

// LovField mapped from table <lov_field>
type LovField struct {
	ID        int64          `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	LovID     int64          `gorm:"column:lov_id;not null" json:"lov_id"`
	Label     string         `gorm:"column:label;not null" json:"label"`
	Value     int16          `gorm:"column:value;not null" json:"value"`
	Desc      string         `gorm:"column:desc" json:"desc"`
	Stauts    int16          `gorm:"column:stauts" json:"stauts"`
}

// TableName LovField's table name
func (*LovField) TableName() string {
	return TableNameLovField
}

func FindListByLovId(lovId int64) (*[]LovField, error)  {
	var list []LovField
	err := model.DB.Where("lov_id = ?", lovId).Find(&list).Error
	if err != nil {
		return nil, err
	}
	return &list, nil
}