// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package lov_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLov = "lov"

// Lov mapped from table <lov>
type Lov struct {
	ID        int64          `gorm:"column:id;primaryKey" json:"id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Code      string         `gorm:"column:code;not null" json:"code"`
	Desc      string         `gorm:"column:desc" json:"desc"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Lov's table name
func (*Lov) TableName() string {
	return TableNameLov
}
