package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"
	"go-gin-example/internal/graph/graph_model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input graph_model.CreateUser) (*graph_model.User, error) {
	user, err := r.UserService.Create(&input)
	if err != nil {
		return nil, err
	}
	return OfUser(user), nil
}

// CreateLov is the resolver for the createLov field.
func (r *mutationResolver) CreateLov(ctx context.Context, input graph_model.CreateLov) (*graph_model.Lov, error) {
	lov, err := r.LovService.Create(&input)
	if err != nil {
		return nil, err
	}
	return OfLov(lov), nil
}

// CreateLovField is the resolver for the createLovField field.
func (r *mutationResolver) CreateLovField(ctx context.Context, input graph_model.CreateLovField) (*graph_model.LovField, error) {
	panic(fmt.Errorf("not implemented: CreateLovField - createLovField"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination graph_model.Pagination, usersInput *graph_model.UsersInput) (*graph_model.Users, error) {
	users, err := r.UserService.FindList(&pagination, usersInput)
	if err != nil {
		return nil, err
	}
	total, err := r.UserService.FindTotal(usersInput)
	if err != nil {
		return nil, err
	}
	return &graph_model.Users{
		Total: int(total),
		Data:  OfUsers(users),
	}, nil
}

// LovPage is the resolver for the lovPage field.
func (r *queryResolver) LovPage(ctx context.Context, pagination graph_model.Pagination, lovPageInput *graph_model.LovPageInput) (*graph_model.LovPage, error) {
	list, err := r.LovService.List(&pagination, lovPageInput)
	if err != nil {
		return nil, err
	}
	total, err := r.LovService.Total(lovPageInput)
	if err != nil {
		return nil, err
	}
	return &graph_model.LovPage{
		Total: int(total),
		Data:  OfLovList(list),
	}, nil
}

// LovFields is the resolver for the lovFields field.
func (r *queryResolver) LovFields(ctx context.Context) ([]*graph_model.LovField, error) {
	panic(fmt.Errorf("not implemented: LovFields - lovFields"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
